version: 1
name: "base"
prompts:
  - id: "qa-short"
    input: { question: "What is NRF and why bytes canon?" }
    max_tokens: 256
    judge: "concise-facts"
  - id: "code-medium"
    input: { task: "Write RFC3339 parser in Rust with tests." }
    max_tokens: 512
    judge: "compiles-tests"
  - id: "reason-long"
    input: { case: "Summarize two contradicting docs and produce decision memo." }
    max_tokens: 1024
    judge: "structure-coverage"
